spring.application.name=vanopt
spring.datasource.url=jdbc:postgresql://localhost:5433/vanopt
spring.datasource.username=vanopt
spring.datasource.password=vanopt
spring.jpa.hibernate.ddl-auto=validate
spring.flyway.enabled=true

springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs